### PR TITLE
Prevent too many views being removed by back button.

### LINKED ISSUE #3847: Clicking that topic 'back button' too fast results in an empty topic
Browser: Firefox 37
branch: develop

steps to reproduce:
1. Go to a node that's at least 3 levels deep.
2. Rapidly click on the 'back' button.
3. Get this:

image

image

  4.) (non-)profit.

### PR DESCRIPTION
**Pull request by rtibbles**
Fixes #3847.

### CODE REVIEW

File: kalite/distributed/static/js/distributed/topics/views.js [hunk 1]
```diff
@@ -671,7 +674,6 @@ window.TopicContainerOuterView = BaseView.extend({
     },
 
     back_to_parent: function() {
-        this.remove_topic_views(1);
```
Comment (rtibbles) [inline kalite/distributed/static/js/distributed/topics/views.js]: This is the important change here. The rest is just cleanup of unused back button code.

**Comment by aronasorman** [comment]
I cannot replicate the bug anymore.
