### PR TITLE
Device link fix

### LINKED ISSUE #3786: Sync now button produces broken link
On `develop`.
To reproduce: Create admin account and register device. Subsequently on the zone management page, you'll find the link "Sync Now!" in the devices table. Clicking the link causes an alert bubble to appear on the page with a broken link.

### PR DESCRIPTION
**Pull request by MCGallaspy**
Fixes #3786.

### CODE REVIEW

File: kalite/distributed/static/js/distributed/distributed-server.js [hunk 1]
```diff
@@ -35,14 +35,14 @@ function show_api_messages(messages) {
...
-function force_sync() {
+function force_sync(zone_id, device_id) {
     // Simple function that calls the API endpoint to force a data sync,
     //   then shows a message for success/failure
     doRequest(window.Urls.api_force_sync())
         .success(function() {
             var msg = gettext("Successfully launched data syncing job.") + " ";
             msg += sprintf(gettext("After syncing completes, visit the <a href='%(devman_url)s'>device management page</a> to view results."), {
-                devman_url: window.sessionModel.get("LOCAL_DEVICE_MANAGEMENT_URL")
+                devman_url: Urls.device_management(zone_id, device_id)
```
Comment (rtibbles) [inline kalite/distributed/static/js/distributed/distributed-server.js]: Urls. Woot!

**Comment by rtibbles** [comment]
Does what it says on the tin:
image
