### PR TITLE
Fixes redirect for modal login.

### LINKED ISSUE #3538: Getting logged out refreshes the page, but doesn't bring up the modal.
When I restart the server, it logs me out (expected), but it simply leads me to this:
login

And doesn't show the modal anywhere. In develop, but maybe it's extant in 0.13.x too.

### PR DESCRIPTION
**Pull request by rtibbles**
Fixes #3538

Summary of changes:
* Use next GET param to determine redirect location.
* If no next GET param, then use any supplied redirect from the API response
* Alter the 403 handler view to add login=true to the GET param to trigger the modal.

### CODE REVIEW

File: kalite/distributed/static/js/distributed/user/views.js [hunk 1]
```diff
@@ -299,15 +312,25 @@ window.UserView = BaseView.extend({
                 this.totalPointViewXs = new TotalPointView({model: this.model, el: "#points-xs"});
             }
         } else {
+            var options = {};
+            var next = getParamValue("next");
+            var login = getParamValue("login");
+            if (login || this.login_start_open) {
+                options.start_open = true;
+
+                delete this.login_start_open;
```
Comment (jamalex) [inline kalite/distributed/static/js/distributed/user/views.js]: Some comments in here (and a few more, in general) could be helpful -- not clear to me what this variable (`login_start_open`) means, or why it's being deleted rather than set to `false`, etc.

File: kalite/distributed/static/js/distributed/user/views.js [hunk 2]
```diff
@@ -89,6 +97,11 @@ window.LoginView = BaseView.extend({
     handle_login: function(response) {
         if (response.status == 200) {
             this.trigger("login_success");
```
Comment (MCGallaspy) [inline kalite/distributed/static/js/distributed/user/views.js]: Does this set up the potential for a race condition? Maybe "login_success" should only be triggered if a redirect doesn't occur. Otherwise it's possible someone might come to expect a side effect from the "login_success" event that occurs before the page reloads, which isn't a safe expectation.

Comment (rtibbles) [inline kalite/distributed/static/js/distributed/user/views.js]: I am not sure what that side effect might be. This is being used to close the modal upon success, which is a reasonable UI expectation regardless of whether the page subsequently redirects (from a user point of view the modal dismissing is a good indicator of the login success, even if momentarily).

Unless this event was being used to trigger some server side logging, I don't know how this could possibly result in an unsafe expectation.

Comment (MCGallaspy) [inline kalite/distributed/static/js/distributed/user/views.js]: > I don't know how this could possibly result in an unsafe expectation.

It doesn't right now, but my point is that it could in the future if someone decides to add another listener. Since this _could_ trigger a page load (yet _may_ not), any listener will have to finish what it's doing in a hurry or potentially be cut short. If all you wish to do is close the modal, why not just call `close_modal` directly?

Comment (rtibbles) [inline kalite/distributed/static/js/distributed/user/views.js]: Because the modal logic is separated from the interior login view.

Comment (MCGallaspy) [inline kalite/distributed/static/js/distributed/user/views.js]: Okay, point taken. It's unlikely this will be used in an unsafe way.

File: kalite/distributed/static/js/distributed/user/views.js (hunk 1 above)
Comment (rtibbles) [inline kalite/distributed/static/js/distributed/user/views.js]: I... think this got left in from another approach I took to this. I will delete this flag.

**Comment by rtibbles** [comment]
Comments addressed. Rebased to latest develop to hopefully get tests to pass.

**Comment by MCGallaspy** [comment]
It appears there are some test failures here because the redirect logic has changed. I wonder if `LoginRequiredTestCase` can be removed? I'll take a look.

**Comment by MCGallaspy** [comment]
Huh, weird, just noticed it's a django test. Why are we even running that?

**Comment by rtibbles** [comment]
That is odd. Even more odd, is the fact that previously the URLs were just bare URLs, and so would have failed the reverse lookup that is causing the failure here too...

**Comment by rtibbles** [comment]
Should also fix #3544

**Comment by rtibbles** [comment]
Tests pass, merging.
