### PR TITLE
Ensure attempt logs are given exercise_id, and inserted in right order.

### LINKED ISSUE #5017: Red crosses for incorrect exercises will vanish if the user refresh the page.
## Summary

This is in a `Functional Testing Checklist` of every installers.
`Do some exercise items incorrectly, refresh the page and make sure both incorrect and correct points (green check marks and red crosses are still there).`
When testing this the red crosses for incorrect exercises, will vanish if the learner refresh the page.

I tested this in OS X Yosemite and using Google Chrome browser.

## Branch or installer method

 - Version: 0.16.x

or:

 - Branch: 0.16.x

## How to reproduce

1. Login as learner
1. Do some exercise items incorrectly.
1. Refresh the page.  

## Screenshots
screen shot 2016-03-18 at 2 51 24 pm
Taking exercises with 3 incorrect answers.

screen shot 2016-03-18 at 2 56 36 pm
Red crosses will vanish after a refresh.

### PR DESCRIPTION
**Pull request by jamalex**
## Summary

Due to some refactoring, we were no longer setting `exercise_id` when saving an `AttemptLog`. This means there was no way of know what exercise it was for, which was messing up coach reports, syncing (it was a required field, and hence caused failed validation), and exercises (refreshing the page would make attempts disappear).

Minimal changes here, but they fix all of these issues.

## Issues addressed

Fixes #5017 and #4989.

### CODE REVIEW

File: kalite/distributed/static/js/distributed/exercises/views.js [hunk 1]
```diff
@@ -564,7 +564,7 @@ var ExerciseWrapperBaseView = BaseView.extend({
 
         this.current_attempt_log = new Models.AttemptLogModel(data);
 
-        this.attempt_collection.add(this.current_attempt_log);
+        this.attempt_collection.unshift(this.current_attempt_log);
```
Comment (jamalex) [inline kalite/distributed/static/js/distributed/exercises/views.js]: Attempt marks (X and checks) were being added to the lefthand side, but then showing back up on the right when refreshed. This fixes that.

**Comment by rtibbles** [comment]
Looks like the right fix to me.
